### ISSUE TITLE
Add support for Debian

### ISSUE THREAD

**Issue by nmadhok** [saltstack-formulas/wordpress-formula#1]
Debian support needs to be added

**Comment by Laogeodritt** [comment]
I'm currently basing myself on this formula for a Debian system... I'm also reworking this to be more flexible (e.g. in my case I want to install it in /srv/data/<sitename> rather than /var/www; allowing more flexible wp-config configuration via a pillar).

Will fork and make a pull req when I have a chance to clean it up that it's releasable.

**Comment by bogdanr** [comment]
:+1:

**Comment by fintanmm** [comment]
The pillar lookup can be used to change the base install directory. Please add distro defaults to map.jinja. 
Closing for now.
